spring:
  webflux:
    cors:
      exposed-headers: ''
      max-age: '3600'
      allow-credentials: 'true'
      allowed-methods: GET,POST,PUT,DELETE
      allowed-headers: '*'
      allowed-origins: '*'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/crud
  mail:
    host: localhost
    username: noreply@testemail.com
    password: test
    port: 1025
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.auth: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  servlet:
    context-path: /api/web-store
